export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const GET_ALL_COUNTRIES_BY_NAME = "GET_ALL_COUNTRIES_BY_NAME";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const POST_ACTIVITY = "POST_ACTIVITY"
export const DELETE_ACTIVITY = "DELETE_ACTIVITY"
export const CLEAN_DB = "CLEAN_DB"
export const ORDER_COUNTRIES = "ORDER_COUNTRIES"
export const ORDER_CONTINENTS = "ORDER_CONTINENTS"
export const ORDER_POBLATION = "ORDER_POBLATION"

export const ALL = "ALL"